name: C
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        nim-version: stable
    - name: Build test DLL
      run: nim c --gc:arc --app:lib -o:tests/generated/test tests/test.nim
    - name: Compile C test (Linux)
      if: runner.os == 'Linux'
      run: gcc -o tests/test_c tests/test_c.c -I tests/generated -L tests/generated -l:libtest.so -Wl,-rpath,'$ORIGIN/generated'
    - name: Compile C test (Windows)
      if: runner.os == 'Windows'
      run: gcc -o tests/test_c.exe tests/test_c.c -I tests/generated -L tests/generated -ltest
    - name: Run C test (Linux)
      if: runner.os == 'Linux'
      run: ./tests/test_c
    - name: Run C test (Windows)
      if: runner.os == 'Windows'
      run: |
        $env:PATH = "tests\generated;" + $env:PATH
        .\tests\test_c.exe
